# Generated by Django 3.2.8 on 2021-12-14 03:42

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item3',
            fields=[
                ('studentid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('studentname', models.CharField(max_length=50)),
                ('organizationtype', models.CharField(blank=True, max_length=15, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=service.models.filepath)),
                ('email', models.CharField(max_length=30)),
                ('biographic_info', models.CharField(max_length=200)),
                ('academic_info', models.CharField(max_length=200)),
                ('financial_info', models.CharField(max_length=200)),
            ],
        ),
    ]
